services:
  signaling-server:
    container_name: signaling-server
    build:
      context: ./server
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./client
    env_file:
      - client/.env
    ports:
      - "80:80"
    depends_on:
      - signaling-server
